"""
BTC Trend Trader Professional v4
Analytics Panel
"""

from __future__ import annotations

from analytics.duration_formatter import DurationFormatter


class AnalyticsPanel:
    """
    Displays analytics generated by AnalyticsService.
    """

    def __init__(self):

        self.analytics = {}

        self.duration_formatter = DurationFormatter()

    # -------------------------------------------------

    def update(
        self,
        analytics,
    ):

        self.analytics = analytics

    # -------------------------------------------------

    def render(self):

        if not self.analytics:
            return

        print("\nANALYTICS")
        print("-" * 60)

        #
        # Drawdown
        #

        drawdown = self.analytics.get(
            "drawdown",
            {},
        )

        print(
            f"Current Equity          : "
            f"{drawdown.get('current_equity', 0)}"
        )

        print(
            f"Peak Equity             : "
            f"{drawdown.get('peak_equity', 0)}"
        )

        print(
            f"Current Drawdown        : "
            f"{drawdown.get('current_drawdown', 0)}"
        )

        print(
            f"Maximum Drawdown        : "
            f"{drawdown.get('maximum_drawdown', 0)}"
        )

        print(
            f"Maximum Drawdown (%)    : "
            f"{drawdown.get('maximum_drawdown_percent', 0)}"
        )

        #
        # Streak Analysis
        #

        streak = self.analytics.get(
            "streak_analysis",
            {},
        )

        print(
            f"Current Win Streak      : "
            f"{streak.get('current_win_streak', 0)}"
        )

        print(
            f"Current Loss Streak     : "
            f"{streak.get('current_loss_streak', 0)}"
        )

        print(
            f"Longest Win Streak      : "
            f"{streak.get('longest_win_streak', 0)}"
        )

        print(
            f"Longest Loss Streak     : "
            f"{streak.get('longest_loss_streak', 0)}"
        )

        #
        # Trade Duration
        #

        duration = self.analytics.get(
            "trade_duration",
            {},
        )

        print("\nTRADE DURATION")
        print("-" * 60)

        print(
            f"Average Duration        : "
            f"{self.duration_formatter.format(duration.get('average_duration', 0))}"
        )

        print(
            f"Shortest Trade          : "
            f"{self.duration_formatter.format(duration.get('shortest_duration', 0))}"
        )

        print(
            f"Longest Trade           : "
            f"{self.duration_formatter.format(duration.get('longest_duration', 0))}"
        )

        print(
            f"Average Winning Trade   : "
            f"{self.duration_formatter.format(duration.get('average_winning_duration', 0))}"
        )

        print(
            f"Average Losing Trade    : "
            f"{self.duration_formatter.format(duration.get('average_losing_duration', 0))}"
        )

        #
        # Risk Metrics
        #

        risk = self.analytics.get(
            "risk_metrics",
            {},
        )

        print("\nRISK METRICS")
        print("-" * 60)

        print(
            f"Sharpe Ratio            : "
            f"{risk.get('sharpe_ratio', 0)}"
        )

        print(
            f"Sortino Ratio           : "
            f"{risk.get('sortino_ratio', 0)}"
        )

        print(
            f"Calmar Ratio            : "
            f"{risk.get('calmar_ratio', 0)}"
        )