"""
BTC Trend Trader Professional v4
Analytics Panel
"""

from __future__ import annotations


class AnalyticsPanel:
    """
    Displays analytics generated by AnalyticsService.
    """

    def __init__(self):

        self.analytics = {}

    # -------------------------------------------------

    def update(
        self,
        analytics,
    ):

        self.analytics = analytics

    # -------------------------------------------------

    def render(self):

        if not self.analytics:
            return

        print("\nANALYTICS")
        print("-" * 60)

        #
        # Drawdown
        #

        drawdown = self.analytics.get(
            "drawdown",
            {},
        )

        print(
            f"Current Equity          : "
            f"{drawdown.get('current_equity', 0)}"
        )

        print(
            f"Peak Equity             : "
            f"{drawdown.get('peak_equity', 0)}"
        )

        print(
            f"Current Drawdown        : "
            f"{drawdown.get('current_drawdown', 0)}"
        )

        print(
            f"Maximum Drawdown        : "
            f"{drawdown.get('maximum_drawdown', 0)}"
        )

        print(
            f"Maximum Drawdown (%)    : "
            f"{drawdown.get('maximum_drawdown_percent', 0)}"
        )

        #
        # Streaks
        #

        streak = self.analytics.get(
            "streak_analysis",
            {},
        )

        print(
            f"Current Win Streak      : "
            f"{streak.get('current_win_streak', 0)}"
        )

        print(
            f"Current Loss Streak     : "
            f"{streak.get('current_loss_streak', 0)}"
        )

        print(
            f"Longest Win Streak      : "
            f"{streak.get('longest_win_streak', 0)}"
        )

        print(
            f"Longest Loss Streak     : "
            f"{streak.get('longest_loss_streak', 0)}"
        )